---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-toml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '80']

- repo: https://github.com/adrienverge/yamllint
  rev: v1.38.0
  hooks:
  - id: yamllint
    args: [-f, parsable, -d, relaxed]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix, --ignore, D1]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.20.2
  hooks:
  - id: mypy
    additional_dependencies: [pydantic>=2, types-requests]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.12
  hooks:
  - id: actionlint

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
