---
resource_types:
  - name: pypi
    type: registry-image
    source:
      repository: mitodl/concourse-pypi-resource

resources:
  - name: ol-concourse
    type: git
    icon: github
    source:
      uri: https://github.com/mitodl/ol-concourse
      branch: main
      paths:
        - pipeline_lib/pyproject.toml
        - pipeline_lib/src/**

  - name: ol-concourse-pypi
    type: pypi
    icon: language-python
    source:
      name: ol-concourse
      username: ((pypi.username))
      password: ((pypi.password))

jobs:
  - name: publish-ol-concourse-lib
    public: true
    plan:
      - get: ol-concourse
        trigger: true
      - task: build-package
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/astral-sh/uv
              tag: latest
          inputs:
            - name: ol-concourse
          outputs:
            - name: dist
          run:
            path: uv
            args:
              - build
              - --directory
              - ol-concourse/pipeline_lib
              - --out-dir
              - dist/
      - put: ol-concourse-pypi
        params:
          glob: dist/ol_concourse-*.tar.gz
